[package]
name = "rustlet"
version = "0.1.0"
authors = ["Joshua Davey <josh@suiteness.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5"
bitflags = "2"
clap = "2"
